highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://NicholasEssel.github.io
author: Nicholas Essel

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: http://NicholasEssel.github.io
title: Nicholas Essel's Resume
name: Nicholas Essel
email_full: mailto:nicholasg.essel@gmail.com
website: github.io/gyasie87
website_full: http://NicholasEssel.github.io
github: trending
tel: +46 707170469
tel_full: tel:+46 707170469
google_maps: 'https://www.google.com/maps/place/Emils+gata+21,+168+72+Bromma'
address:
  street: Emils Gata 21
  postcode: 168 72
  city: Stockholm
  country: Sweden
google_analytics: G-WXTLEDKBGY

# needed for travis-ci build
exclude: [vendor]
